name: di_storage
description: "Example of DiStorage library usage"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
repository: https://github.com/AlexeyYuPopkov/di_storage_dart
issue_tracker: https://github.com/pese-git/cherrypick/issues

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.27.7
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2

  di_storage:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

